site_name: Nome do Projeto
theme:
  name: material # or other theme
  palette:
    primary: blue
  language: en

repo_name: "usuario/projeto"
repo_url: "https://github.com/usuario/projeto" # Para hospedar a documentação no github

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python